name: Push main to Jugit

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: FZJ-IEK3-VSA/CuCoPy
          fetch-depth: 0
      - name: Push To Gitlab
        env:
          token: ${{ secrets.GITLAB_ACCESS_TOKEN }}
        run: |
          echo Starting to push repo to gitlab
          git config user.name "maxime-gorres-auto-commit"
          git config user.email "m.gorres@fz-juelich.de"
          echo user name and email are set
          git fetch
          git switch main
          echo "Checkout complete"
          echo start to push
          git push https://push_to_jugit:${{ secrets.GITLAB_ACCESS_TOKEN }}@jugit.fz-juelich.de/iek-3/groups/data-and-model-integration/cucopy.git main
          echo push done